lab3: rbtree.h wordcounts.h filereader.h wordcounts.cpp rbtree.cpp\
filereader.cpp main.cpp
	g++ -g -o lab3 -Wall -pedantic -lrt rbtree.cpp\
        wordcounts.cpp filereader.cpp main.cpp
clean:
	rm -f lab3

